import { chromium } from "playwright-core"; import http from "node:http"; import fs from "node:fs"; import path from "node:path"; import { fileURLToPath } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../.."); const mime = { ".html": "text/html", ".js": "text/javascript" };
const srv = http.createServer((q, s) => { let f = path.join(root, decodeURIComponent(new URL(q.url, "http://x").pathname)); if (fs.existsSync(f) && fs.statSync(f).isDirectory()) f = path.join(f, "index.html"); if (!fs.existsSync(f) || fs.statSync(f).isDirectory()) { s.writeHead(404); return s.end(); } s.writeHead(200, { "content-type": mime[path.extname(f)] || "text/plain" }); fs.createReadStream(f).pipe(s); });
await new Promise(r => srv.listen(0, "127.0.0.1", r)); const base = `http://127.0.0.1:${srv.address().port}/kit/test/`;
const exe = path.join(process.env.LOCALAPPDATA, "ms-playwright", "chromium_headless_shell-1234", "chrome-headless-shell-win64", "chrome-headless-shell.exe");
const b = await chromium.launch({ executablePath: exe }); const p = await b.newPage({ viewport: { width: 800, height: 500 } }); const out = [];
await p.route("**/app.js*", r => r.abort()); await p.goto(base); await p.waitForTimeout(1500);
out.push(["boot: retried once", p.url().includes("?r=")], ["boot: panel shown", !!(await p.$(".ag-panel h1"))]);
await p.unroute("**/app.js*"); await p.goto(base); await p.waitForTimeout(500);
out.push(["healthy: no panel", !(await p.$(".ag-panel"))]);
await p.click("#boom"); await p.waitForTimeout(300);
out.push(["runtime error: inline panel", (await p.$eval(".ag-panel.ag-inline h1", e => e.textContent)) === "Something went wrong"], ["runtime error: rail area kept (inline mount)", !!(await p.$("#main .ag-panel"))]);
await p.screenshot({ path: path.join(root, "kit/test/error-panel.png") });
await p.goto(base); await p.click("#net"); await p.waitForTimeout(500);
out.push(["network fail copy", (await p.$eval(".ag-panel h1", e => e.textContent)) === "Can't reach the system right now"]);
await p.goto(base); await p.context().setOffline(true); await p.waitForTimeout(300);
out.push(["offline banner", !!(await p.$(".ag-offline"))]); await p.context().setOffline(false); await p.waitForTimeout(300);
out.push(["online clears banner", !(await p.$(".ag-offline"))]);
for (const [n, ok] of out) console.log(ok ? "PASS" : "FAIL", n); await b.close(); srv.close(); process.exit(out.every(o => o[1]) ? 0 : 1);
